export const  menuList = [
  {
    key: 'home',
    pkey: 0,
    code: "ics.document.contentManage",
    label: "内容管理",
    // icon: "fuwuneirong",
    href: "/home",
    sorting: 2,
    children: [
      {
        key: 'home',
        pkey: 32,
        code: "ics.document.contentManage.materialLibrary",
        label: "素材库",
        icon: "",
        href: "/home",
        sorting: 1,
        children: null,
      },
    ],
  },
  {
    key: 'about',
    pkey: 0,
    code: "ics.document.configuration",
    label: "配置中心",
    // icon: "renwu",
    href: "/about",
    sorting: 4,
    children: [
      {
        key: 'about',
        pkey: 34,
        code: "ics.document.configuration.siteManage",
        label: "站点管理",
        icon: "",
        href: "/about",
        sorting: 1,
        children: null,
      },
    ],
  },
  {
    key: 'counter',
    pkey: 0,
    code: "ics.document.dataCenter",
    label: "数据中心",
    // icon: "bingtu",
    href: "/counter",
    sorting: 5,
    children: [
      {
        key: 'counter',
        pkey: 35,
        code: "ics.document.dataCenter.downloadCenter",
        label: "下载中心",
        icon: "",
        href: "/counter",
        sorting: 1,
        children: null,
      },
    ],
  },
];
